bank/achievement/urls.py
from django.conf.urls import url

from bank.achievement import views

urlpatterns = [

    url(r'^new/$', views.achievement_new, name='new'),
    url(r'^card/new/$', views.card_new, name='card_new'),
    url(r'^(?P<pk>[0-9]+)/card/edit/$', views.card_edit, name='card_edit'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.achievement_edit, name='edit'),


]

bank/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from bank import views
from bank.user import urls as user_urls
from bank.achievement import urls as ach_urls

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^user/', include(user_urls, namespace='user')),
    url(r'^achievement/', include(ach_urls, namespace='achievement')),
    url(r'^admin/', include(admin.site.urls))


]

bank/user/urls.py
from django.conf.urls import url

from bank.user import views

urlpatterns = [

    url(r'^registration/$', views.registration, name='registration'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^profile/$', views.profile, name='profile'),

]

bank/models.py
from django.contrib import admin
from django.contrib.auth.models import AbstractBaseUser
from django.db import models
from datetime import datetime, timedelta


from bank.managers import UserManager


class User(AbstractBaseUser):
    username = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    login = models.CharField(max_length=50, unique=True)
    date_of_birth = models.CharField(max_length=50, null=True, blank=True)
    phone_number = models.IntegerField(null=True, blank=True)
    about_user = models.TextField(null=True, blank=True)
    email = models.EmailField()
    password = models.CharField(max_length=50)
    avatar = models.ImageField(upload_to='avatar/%Y/%m/%d/')
    level_points = models.IntegerField(null=True, blank=True)

    objects = UserManager()

    REQUIRED_FIELDS = ('username', 'email')
    USERNAME_FIELD = 'login'

    class Meta:
        db_table = 'user'

    def __str__(self):
        return self.username

    def get_full_name(self):
        return '{} {}'.format(self.username, self.surname)

    def get_short_name(self):
        return self.username

    @property
    def is_auth(self, request):
        user_session = request['user-session']
        session = Session.objects.filter(token=user_session).last()
        if session:
            return True


class Card(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    color = models.CharField(max_length=6, null=True, blank=True)

    class Meta:
        db_table = 'card'

    def __str__(self):
        return self.name


class Achievement(models.Model):
    name = models.CharField(max_length=50)
    text = models.TextField()
    update_data = models.DateTimeField(auto_now=True)
    card = models.ForeignKey(Card, on_delete=models.CASCADE)

    class Meta:
        db_table = 'achievement'

    def __str__(self):
        return self.name


class AchievementResource(models.Model):
    resource_id = models.IntegerField(auto_created=True)
    resource_type = models.IntegerField(choices=(
        (1, 'file'),
        (2, 'link')))
    update_data = models.DateTimeField(auto_now=True)
    achievement = models.ForeignKey(Achievement, on_delete=models.CASCADE)

    class Meta:
        db_table = 'achievement_resource'

    def __str__(self):
        return '{}, {}'.format(self.resource_type, self.achievement)


class Links(models.Model):
    link = models.URLField()
    achievement_resource = models.ForeignKey(AchievementResource, on_delete=models.CASCADE)

    class Meta:
        db_table = 'link'

    def __str__(self):
        return '{}, {}'.format(self.link, self.achievement_resource)


class File(models.Model):
    file = models.FileField(upload_to='resource/%Y/%m/%d/')
    achievement_resource = models.ForeignKey(AchievementResource, on_delete=models.CASCADE)

    class Meta:
        db_table = 'file'


class Label(models.Model):
    text = models.CharField(max_length=30)
    color = models.CharField(max_length=6, null=True, blank=True)

    class Meta:
        db_table = 'label'

    def __str__(self):
        return '{}'.format(self.text)


class AchievementLabel(models.Model):
    label = models.ForeignKey(Label, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    achievement = models.ForeignKey(Achievement, on_delete=models.CASCADE)

    class Meta:
        db_table = 'achievement_label'

    def __str__(self):
        return '{}, {}, {}'.format(self.label, self.user, self.achievement)


class Observer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    card = models.ForeignKey(Card, on_delete=models.CASCADE)

    class Meta:
        db_table = 'observer'

    def __str__(self):
        return '{}, {}'.format(self.user, self.card)


class Session(models.Model):
    user = models.ForeignKey(User)
    token = models.CharField(max_length=36)
    date_expired = models.DateTimeField(default=datetime.now() + timedelta(days=7))

    class Meta:
        db_table = 'session'

admin.site.register(User)
admin.site.register(Card)
admin.site.register(Achievement)
admin.site.register(AchievementResource)
admin.site.register(AchievementLabel)
admin.site.register(Observer)

bank/achievement/forms.py
from django import forms
from bank.models import Achievement, Card


class AchievementForm(forms.ModelForm):
        class Meta:
            model = Achievement
            fields = ('name', 'text', 'card')


class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = ('name', 'color')

bank/user/forms.py
from django import forms
from django.contrib.auth.hashers import check_password
from bank.models import User


class RegistrationForm(forms.Form):
    login = forms.CharField(max_length=50, initial='')
    username = forms.CharField(max_length=50, initial='')
    surname = forms.CharField(max_length=50, initial='')
    email = forms.EmailField(initial='')
    password = forms.CharField(min_length=6, initial='')

    def clean_login(self):
        login = self.cleaned_data['login']
        if User.objects.filter(login=login).first():
            raise forms.ValidationError('login %s already exist' % login)
        return login


class LoginForm(forms.Form):
    login = forms.CharField(max_length=50, initial='')
    password = forms.CharField(min_length=6, initial='')

    def clean(self):
        cleaned_data = super().clean()
        login = cleaned_data['login']
        password = cleaned_data['password']
        self.user = User.objects.filter(login=login).first()
        if not (self.user and check_password(password, self.user.password)):
            raise forms.ValidationError('Incorrect login or password')
        return login


class PasswordChangeForm(forms.Form):
    password = forms.CharField(min_length=6, initial='')
    new_password = forms.CharField(min_length=6, initial='')
    reenter_password = forms.CharField(min_length=6, initial='')

    def clean(self):

        cleaned_data = super().clean()
        password = cleaned_data['password']
        new_password = cleaned_data['new_password']
        reenter_password = cleaned_data['reenter_password']
        if not (new_password == reenter_password or new_password != password):
            raise forms.ValidationError('Incorrect password')
        else:
            return cleaned_data

bank/achievement/views.py
from django.shortcuts import render, redirect, get_object_or_404

from bank.achievement.forms import AchievementForm, CardForm
from bank.models import Achievement, Card


def card_new(request):
    if request.method == 'POST':
        form = CardForm(data=request.POST)
        if form.is_valid():
            card = form.save(commit=False)
            card.user = request.user
            card.save()
            return redirect('user:profile')
    else:
        form = CardForm()
    return render(request, 'achievement/achievement_edit.html', context={'form': form})


def card_edit(request, pk):
    card = get_object_or_404(Card, pk=pk)
    if request.method == 'POST':
        form = CardForm(data=request.POST, instance=card)
        if form.is_valid():
            card = form.save(commit=False)
            card.user = request.user
            card.save()
            return redirect('user:profile')
    else:
        form = CardForm(instance=card)
    return render(request, 'achievement/card_edit.html', context={'form': form})


def achievement_new(request):
    if request.method == 'POST':
        form = AchievementForm(data=request.POST)
        if form.is_valid():
            achievement = form.save(commit=False)
            achievement.user = request.user
            achievement.save()
            return redirect('user:profile')
    else:
        form = AchievementForm()
    return render(request, 'achievement/achievement_edit.html', context={'form': form})


def achievement_edit(request, pk):
        achievement = get_object_or_404(Achievement, pk=pk)
        if request.method == "POST":
            form = AchievementForm(request.POST, instance=achievement)
            if form.is_valid():
                achievement = form.save(commit=False)
                achievement.user = request.user
                achievement.save()
                return redirect('user:profile')
        else:
            form = AchievementForm(instance=achievement)
        return render(request, 'achievement/achievement_edit.html', {'form': form})

bank/user/views.py
from django.shortcuts import render, redirect
import uuid

from bank.user.forms import RegistrationForm, LoginForm, PasswordChangeForm
from bank.models import User, Session, Card, Achievement


def registration(request):
    if request.method == 'POST':
        form = RegistrationForm(data=request.POST)
        if form.is_valid():
            if not User.objects.registration(
                form.cleaned_data['login'],
                form.cleaned_data['password'],
                form.cleaned_data['username'],
                form.cleaned_data['surname'],
                form.cleaned_data['email']
            ):
                pass
            return redirect('user:login')
    else:
        form = RegistrationForm()
    return render(request, 'user/registration.html',
                  context={'form': form})


def login(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            session = Session.objects.create(user=form.user, token=uuid.uuid4())
            response = redirect('/')
            response.set_cookie('user-session', session.token,
                                expires=session.date_expired)
            return response
        else:
            pass

    else:
        form = LoginForm()

    return render(request, 'user/login.html', context={'form': form})


def logout(request):
    user_session = request.COOKIES['user-session']
    session = Session.objects.filter(token=user_session).last()
    if session.delete():
        return redirect('user:login')
    else:
        pass


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST)
        if form.is_valid():
            new_pass = form.cleaned_data['new_password']
            User.objects.change_password(new_pass, request.user.id)
            return redirect('user:login')
        else:
            pass
    else:
        form = PasswordChangeForm()
    return render(request, 'user/change_password.html', context={'form': form})


def profile(request):
    cards = Card.objects.filter(user=request.user).order_by('name')
    achievements = Achievement.objects.all().order_by('name')
    return render(request, 'user/profile.html', {'cards': cards,
                                                 'achievements': achievements})

bank/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from bank import models

def index(request):
    return render(request, 'index.html')

bank/templates/user/change_password.html
{% extends "base.html" %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="../../static/login_register.css">
    {% if form.errors %}
        {{ form.errors }}
    {% endif %}
    <form action="" method="post">
      {% csrf_token %}
        <div class="form-group">
          <label for="login">Login</label>
          <input class="form-control" id="login" name="login" placeholder="Login" value="{{ form.login.value }}">
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" class="form-control" id="password" name="password" placeholder="Password" value="{{ form.password.value }}">
        </div>
        <div class="form-group">
          <label for="new_password">New password</label>
          <input type="password" class="form-control" id="new_password" name="new_password" placeholder="New password" value="{{ form.new_password.value}}">
        </div>
        <div class="form-group">
          <label for="reenter_password">Reenter password</label>
          <input type="password" class="form-control" id="reenter_password" name="reenter_password" placeholder="Reenter password" value="{{ form.reenter_password.value }}">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
{% endblock %}

bank/templates/user/login.html
{% extends "base.html" %}

{% block content %}
<link rel="stylesheet" type="text/css" href="../../static/login_register.css">
<div class="container-fluid">
	 <form action="" method="post" class="register-form">
         {% csrf_token %}
      <div class="row">
           <div class="col-md-4 col-sm-4 col-lg-4">
              <label for="firstName">LOGIN</label>
               <input class="form-control" id="login" name="login" placeholder="Login" value="{{ form.login.value }}">
           </div>
      </div>
      <div class="row">
           <div class="col-md-4 col-sm-4 col-lg-4">
              <label for="password">PASSWORD</label>
               <input type="password" class="form-control" id="password" name="password" placeholder="Password" value="{{ form.password.value }}">
           </div>
      </div>
      <hr>
         <div>
          <div class="col-md-6 col-sm-6 col-xs-6 col-lg-6">
           <button class="btn btn-default logbutton">Sign up</button>
          </div>
      </div>
    </form>
</div>
{% endblock %}

bank/templates/user/logout.html
{% extends "base.html" %}

{% block content %}
    <p>Logged out!</p>

<a href="{% url 'user:login'%}">Click here to login again.</a>
{% endblock %}

bank/templates/user/profile.html
{% extends "base.html" %}

{% block content %}
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <style type="text/css">
   .block {
    width: 200px;
    background: #bcccb4;
    padding: 5px;
    padding-right: 20px;
    margin-top: 100px;
    border: solid 1px black;
    float: left;
   }
    .block_1 {
    width: 200px;
    background: #fc0;
    padding: 5px;
    padding-right: 20px;
    margin-top: 100px;
    border: solid 1px black;
    float: left;
   }
    .block_2 {
    width: 200px;
    background: #ffc5a4;
    padding: 5px;
    padding-right: 20px;
    margin-left: 20px;
    margin-top: 180px;
    border: solid 1px black;
    float: left;
    position: absolute;
   }
      .card {
    width: 200px;
    background: #fffa3b;
    padding: 5px;
    padding-right: 20px;
    margin-top: 5px;
    border: solid 1px black;
    float: left;
    position: relative;
   }
   </style>
    {% if form.errors %}
        {{ form.errors }}}
    {% endif %}
    <div class="block">
       <p><a href="{% url 'achievement:new' %}">Add achievement</a></p>
    </div>
    <div class="block_1">
        <p><a href="{% url 'achievement:card_new' %}">Add Card</a></p>
    </div>
    <div class="block_2">
        <h2>Your cards</h2>
        {% for card in cards %}
            <div class="card">
                <h4>{{ card.name }}
                <a class="btn btn-default" href="{% url 'achievement:card_edit' pk=card.pk %}">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a></h4>
            {% for  achievement in  achievements %}
                {% if achievement.card == card %}
                    <p>{{ achievement.name }}
                        <a class="btn btn-default" href="{% url 'achievement:edit' pk=achievement.pk %}">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                    </p>
                {% endif %}
            {% endfor %}
            </div>
        {% endfor %}

    </div>
{%  endblock %}

bank/templates/user/registration.html
{% extends "base.html" %}

{% block content %}

    {% if form.errors %}
        {{ form.errors }}}
    {% endif %}

<link rel="stylesheet" type="text/css" href="../../static/login_register.css">
<div class="container-fluid">
	 <form action="" method="post" class="register-form">
         {% csrf_token %}
     <div class="row">
       <div class="col-md-4 col-sm-4 col-lg-4">
          <label for="firstName">LOGIN</label>
           <input class="form-control" id="login" name="login" placeholder="Login" value="{{ form.login.value }}">
       </div>
     </div>
      <div class="row">
           <div class="col-md-4 col-sm-4 col-lg-4">
              <label for="firstName">FIRST NAME</label>
               <input class="form-control" id="username" name="username" placeholder="firs name" value="{{ form.username.value }}">
           </div>
      </div>
      <div class="row">
            <div class="col-md-4 col-sm-4 col-lg-4">
               <label for="firstName">SECOND NAME</label>
               <input class="form-control" id="surname" name="surname" placeholder="second name" value="{{ form.surname.value }}">
            </div>
      </div>
     <div class="row">
        <div class="col-md-4 col-sm-4 col-lg-4">
           <label for="firstName">EMAIL</label>
           <input class="form-control" id="email" name="email" placeholder="email" value="{{ form.email.value }}">
        </div>
    </div>
      <div class="row">
           <div class="col-md-4 col-sm-4 col-lg-4">
              <label for="password">PASSWORD</label>
               <input type="password" class="form-control" id="password" name="password" placeholder="Password" value="{{ form.password.value }}">
           </div>
      </div>
      <hr>
         <div class="row">
           <div class="col-md-6 col-sm-6 col-xs-6 col-lg-6">
           <button class="btn btn-default regbutton">Register</button>
          </div>
      </div>
    </form>
</div>
{% endblock %}