bank/achievement/urls.py
from django.conf.urls import url

from bank.achievement import views

urlpatterns = [

    url(r'^new/$', views.achievement_new, name='new'),
    url(r'^card/new/$', views.card_new, name='card_new'),
    url(r'^(?P<pk>[0-9]+)/card/edit/$', views.card_edit, name='card_edit'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.achievement_edit, name='edit'),


]

bank/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from bank import views
from bank.user import urls as user_urls
from bank.achievement import urls as ach_urls

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^user/', include(user_urls, namespace='user')),
    url(r'^achievement/', include(ach_urls, namespace='achievement')),
    url(r'^admin/', include(admin.site.urls))


]

bank/user/urls.py
from django.conf.urls import url

from bank.user import views

urlpatterns = [

    url(r'^registration/$', views.registration, name='registration'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^profile/$', views.profile, name='profile'),

]

bank/models.py
from django.contrib import admin
from django.contrib.auth.models import AbstractBaseUser
from django.db import models
from datetime import datetime, timedelta


from bank.managers import UserManager


class User(AbstractBaseUser):
    username = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    login = models.CharField(max_length=50, unique=True)
    date_of_birth = models.CharField(max_length=50, null=True, blank=True)
    phone_number = models.IntegerField(null=True, blank=True)
    about_user = models.TextField(null=True, blank=True)
    email = models.EmailField()
    password = models.CharField(max_length=50)
    avatar = models.ImageField(upload_to='avatar/%Y/%m/%d/')
    level_points = models.IntegerField(null=True, blank=True)

    objects = UserManager()

    REQUIRED_FIELDS = ('username', 'email')
    USERNAME_FIELD = 'login'

    class Meta:
        db_table = 'user'

    def __str__(self):
        return self.username

    def get_full_name(self):
        return '{} {}'.format(self.username, self.surname)

    def get_short_name(self):
        return self.username

    @property
    def is_auth(self, request):
        user_session = request['user-session']
        session = Session.objects.filter(token=user_session).last()
        if session:
            return True


class Card(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    color = models.CharField(max_length=6, null=True, blank=True)

    class Meta:
        db_table = 'card'

    def __str__(self):
        return self.name


class Achievement(models.Model):
    name = models.CharField(max_length=50)
    text = models.TextField()
    update_data = models.DateTimeField(auto_now=True)
    card = models.ForeignKey(Card, on_delete=models.CASCADE)

    class Meta:
        db_table = 'achievement'

    def __str__(self):
        return self.name


class AchievementResource(models.Model):
    resource_id = models.IntegerField(auto_created=True)
    resource_type = models.IntegerField(choices=(
        (1, 'file'),
        (2, 'link')))
    update_data = models.DateTimeField(auto_now=True)
    achievement = models.ForeignKey(Achievement, on_delete=models.CASCADE)

    class Meta:
        db_table = 'achievement_resource'

    def __str__(self):
        return '{}, {}'.format(self.resource_type, self.achievement)


class Links(models.Model):
    link = models.URLField()
    achievement_resource = models.ForeignKey(AchievementResource, on_delete=models.CASCADE)

    class Meta:
        db_table = 'link'

    def __str__(self):
        return '{}, {}'.format(self.link, self.achievement_resource)


class File(models.Model):
    file = models.FileField(upload_to='resource/%Y/%m/%d/')
    achievement_resource = models.ForeignKey(AchievementResource, on_delete=models.CASCADE)

    class Meta:
        db_table = 'file'


class Label(models.Model):
    text = models.CharField(max_length=30)
    color = models.CharField(max_length=6, null=True, blank=True)

    class Meta:
        db_table = 'label'

    def __str__(self):
        return '{}'.format(self.text)


class AchievementLabel(models.Model):
    label = models.ForeignKey(Label, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    achievement = models.ForeignKey(Achievement, on_delete=models.CASCADE)

    class Meta:
        db_table = 'achievement_label'

    def __str__(self):
        return '{}, {}, {}'.format(self.label, self.user, self.achievement)


class Observer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    card = models.ForeignKey(Card, on_delete=models.CASCADE)

    class Meta:
        db_table = 'observer'

    def __str__(self):
        return '{}, {}'.format(self.user, self.card)


class Session(models.Model):
    user = models.ForeignKey(User)
    token = models.CharField(max_length=36)
    date_expired = models.DateTimeField(default=datetime.now() + timedelta(days=7))

    class Meta:
        db_table = 'session'

admin.site.register(User)
admin.site.register(Card)
admin.site.register(Achievement)
admin.site.register(AchievementResource)
admin.site.register(AchievementLabel)
admin.site.register(Observer)

bank/achievement/forms.py
from django import forms
from bank.models import Achievement, Card


class AchievementForm(forms.ModelForm):
        class Meta:
            model = Achievement
            fields = ('name', 'text', 'card')


class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = ('name', 'color')

bank/user/forms.py
from django import forms
from django.contrib.auth.hashers import check_password
from bank.models import User


class RegistrationForm(forms.Form):
    login = forms.CharField(max_length=50, initial='')
    username = forms.CharField(max_length=50, initial='')
    surname = forms.CharField(max_length=50, initial='')
    email = forms.EmailField(initial='')
    password = forms.CharField(min_length=6, initial='')

    def clean_login(self):
        login = self.cleaned_data['login']
        if User.objects.filter(login=login).first():
            raise forms.ValidationError('login %s already exist' % login)
        return login


class LoginForm(forms.Form):
    login = forms.CharField(max_length=50, initial='')
    password = forms.CharField(min_length=6, initial='')

    def clean(self):
        cleaned_data = super().clean()
        login = cleaned_data['login']
        password = cleaned_data['password']
        self.user = User.objects.filter(login=login).first()
        if not (self.user and check_password(password, self.user.password)):
            raise forms.ValidationError('Incorrect login or password')
        return login


class PasswordChangeForm(forms.Form):
    password = forms.CharField(min_length=6, initial='')
    new_password = forms.CharField(min_length=6, initial='')
    reenter_password = forms.CharField(min_length=6, initial='')

    def clean(self):

        cleaned_data = super().clean()
        password = cleaned_data['password']
        new_password = cleaned_data['new_password']
        reenter_password = cleaned_data['reenter_password']
        if not (new_password == reenter_password or new_password != password):
            raise forms.ValidationError('Incorrect password')
        else:
            return cleaned_data

bank/achievement/views.py
from django.shortcuts import render, redirect, get_object_or_404

from bank.achievement.forms import AchievementForm, CardForm
from bank.models import Achievement, Card


def card_new(request):
    if request.method == 'POST':
        form = CardForm(data=request.POST)
        if form.is_valid():
            card = form.save(commit=False)
            card.user = request.user
            card.save()
            return redirect('user:profile')
    else:
        form = CardForm()
    return render(request, 'achievement/achievement_edit.html', context={'form': form})


def card_edit(request, pk):
    card = get_object_or_404(Card, pk=pk)
    if request.method == 'POST':
        form = CardForm(data=request.POST, instance=card)
        if form.is_valid():
            card = form.save(commit=False)
            card.user = request.user
            card.save()
            return redirect('user:profile')
    else:
        form = CardForm(instance=card)
    return render(request, 'achievement/card_edit.html', context={'form': form})


def achievement_new(request):
    if request.method == 'POST':
        form = AchievementForm(data=request.POST)
        if form.is_valid():
            achievement = form.save(commit=False)
            achievement.user = request.user
            achievement.save()
            return redirect('user:profile')
    else:
        form = AchievementForm()
    return render(request, 'achievement/achievement_edit.html', context={'form': form})


def achievement_edit(request, pk):
        achievement = get_object_or_404(Achievement, pk=pk)
        if request.method == "POST":
            form = AchievementForm(request.POST, instance=achievement)
            if form.is_valid():
                achievement = form.save(commit=False)
                achievement.user = request.user
                achievement.save()
                return redirect('user:profile')
        else:
            form = AchievementForm(instance=achievement)
        return render(request, 'achievement/achievement_edit.html', {'form': form})

bank/user/views.py
from django.shortcuts import render, redirect
import uuid

from bank.user.forms import RegistrationForm, LoginForm, PasswordChangeForm
from bank.models import User, Session, Card, Achievement


def registration(request):
    if request.method == 'POST':
        form = RegistrationForm(data=request.POST)
        if form.is_valid():
            if not User.objects.registration(
                form.cleaned_data['login'],
                form.cleaned_data['password'],
                form.cleaned_data['username'],
                form.cleaned_data['surname'],
                form.cleaned_data['email']
            ):
                pass
            return redirect('user:login')
    else:
        form = RegistrationForm()
    return render(request, 'user/registration.html',
                  context={'form': form})


def login(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            session = Session.objects.create(user=form.user, token=uuid.uuid4())
            response = redirect('/')
            response.set_cookie('user-session', session.token,
                                expires=session.date_expired)
            return response
        else:
            pass

    else:
        form = LoginForm()

    return render(request, 'user/login.html', context={'form': form})


def logout(request):
    user_session = request.COOKIES['user-session']
    session = Session.objects.filter(token=user_session).last()
    if session.delete():
        return redirect('user:login')
    else:
        pass


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST)
        if form.is_valid():
            new_pass = form.cleaned_data['new_password']
            User.objects.change_password(new_pass, request.user.id)
            return redirect('user:login')
        else:
            pass
    else:
        form = PasswordChangeForm()
    return render(request, 'user/change_password.html', context={'form': form})


def profile(request):
    cards = Card.objects.filter(user=request.user).order_by('name')
    achievements = Achievement.objects.all().order_by('name')
    return render(request, 'user/profile.html', {'cards': cards,
                                                 'achievements': achievements})

bank/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from bank import models

def index(request):
    return render(request, 'index.html')

bank/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Bank</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="../static/base.css">
</head>
<body>
<div class="navbar-wrapper">
    <div class="container-fluid">
        <nav class="navbar navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Bank</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class=""><a href="{% url 'index' %}">Home</a></li>

                        <li class=""><a href="{% url 'user:profile' %}">My Profile</a></li>
                    </ul>
                    <ul class="nav navbar-nav pull-right">
                        <li class=" dropdown"><a href="#" class="dropdown-toggle active" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Signed in as {{ user.login }} <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'user:change_password' %}">Change password</a></li>
                                <li class=""><a href="{% url 'user:logout' %}">Log out</a></li>
                            </ul>
                            <li class=""><a href="{% url 'user:login' %}">Log in</a></li>

                        <li class=""><a href="{% url 'user:registration' %}">Registration</a></li>
                    </ul>
                </div>
            </div>
        </nav>
{% block content %}
{% endblock %}

  </div>
</div>
</body>
</html>

bank/templates/index.html
{% extends "base.html" %}

{% block content %}
<link rel="stylesheet" type="text/css" href="../static/index.css">

<div class="container">
<div class="col-xs-12">
    <div class="carousel slide" id="myCarousel">
        <div class="carousel-inner">
            <div class="item active">
                    <ul class="thumbnails">
                        <li class="col-sm-3">
    						<div class="fff">
								<div class="thumbnail">
									<a href="#"><img src="http://placehold.it/360x240" alt=""></a>
								</div>
								<div class="caption">
									<h4>Praesent commodo</h4>
									<p>Nullam Condimentum Nibh Etiam Sem</p>
									<a class="btn btn-mini" href="#">» Read More</a>
								</div>
                            </div>
                        </li>
                        <li class="col-sm-3">
							<div class="fff">
								<div class="thumbnail">
									<a href="#"><img src="http://placehold.it/360x240" alt=""></a>
								</div>
								<div class="caption">
									<h4>Praesent commodo</h4>
									<p>Nullam Condimentum Nibh Etiam Sem</p>
									<a class="btn btn-mini" href="#">» Read More</a>
								</div>
                            </div>
                        </li>
                        <li class="col-sm-3">
							<div class="fff">
								<div class="thumbnail">
									<a href="#"><img src="http://placehold.it/360x240" alt=""></a>
								</div>
								<div class="caption">
									<h4>Praesent commodo</h4>
									<p>Nullam Condimentum Nibh Etiam Sem</p>
									<a class="btn btn-mini" href="#">» Read More</a>
								</div>
                            </div>
                        </li>
                        <li class="col-sm-3">
							<div class="fff">
								<div class="thumbnail">
									<a href="#"><img src="http://placehold.it/360x240" alt=""></a>
								</div>
								<div class="caption">
									<h4>Praesent commodo</h4>
									<p>Nullam Condimentum Nibh Etiam Sem</p>
									<a class="btn btn-mini" href="#">» Read More</a>
								</div>
                            </div>
                        </li>
                    </ul>
              </div><!-- /Slide1 -->
            <div class="item">
                    <ul class="thumbnails">
                        <li class="col-sm-3">
							<div class="fff">
								<div class="thumbnail">
									<a href="#"><img src="http://placehold.it/360x240" alt=""></a>
								</div>
								<div class="caption">
									<h4>Praesent commodo</h4>
									<p>Nullam Condimentum Nibh Etiam Sem</p>
									<a class="btn btn-mini" href="#">» Read More</a>
								</div>
                            </div>
                        </li>
                        <li class="col-sm-3">
							<div class="fff">
								<div class="thumbnail">
									<a href="#"><img src="http://placehold.it/360x240" alt=""></a>
								</div>
								<div class="caption">
									<h4>Praesent commodo</h4>
									<p>Nullam Condimentum Nibh Etiam Sem</p>
									<a class="btn btn-mini" href="#">» Read More</a>
								</div>
                            </div>
                        </li>
                        <li class="col-sm-3">
							<div class="fff">
								<div class="thumbnail">
									<a href="#"><img src="http://placehold.it/360x240" alt=""></a>
								</div>
								<div class="caption">
									<h4>Praesent commodo</h4>
									<p>Nullam Condimentum Nibh Etiam Sem</p>
									<a class="btn btn-mini" href="#">» Read More</a>
								</div>
                            </div>
                        </li>
                        <li class="col-sm-3">
							<div class="fff">
								<div class="thumbnail">
									<a href="#"><img src="http://placehold.it/360x240" alt=""></a>
								</div>
								<div class="caption">
									<h4>Praesent commodo</h4>
									<p>Nullam Condimentum Nibh Etiam Sem</p>
									<a class="btn btn-mini" href="#">» Read More</a>
								</div>
                            </div>
                        </li>
                    </ul>
              </div><!-- /Slide2 -->
            <div class="item">
                    <ul class="thumbnails">
                        <li class="col-sm-3">
							<div class="fff">
								<div class="thumbnail">
									<a href="#"><img src="http://placehold.it/360x240" alt=""></a>
								</div>
								<div class="caption">
									<h4>Praesent commodo</h4>
									<p>Nullam Condimentum Nibh Etiam Sem</p>
									<a class="btn btn-mini" href="#">» Read More</a>
								</div>
                            </div>
                        </li>
                        <li class="col-sm-3">
							<div class="fff">
								<div class="thumbnail">
									<a href="#"><img src="http://placehold.it/360x240" alt=""></a>
								</div>
								<div class="caption">
									<h4>Praesent commodo</h4>
									<p>Nullam Condimentum Nibh Etiam Sem</p>
									<a class="btn btn-mini" href="#">» Read More</a>
								</div>
                            </div>
                        </li>
                        <li class="col-sm-3">
							<div class="fff">
								<div class="thumbnail">
									<a href="#"><img src="http://placehold.it/360x240" alt=""></a>
								</div>
								<div class="caption">
									<h4>Praesent commodo</h4>
									<p>Nullam Condimentum Nibh Etiam Sem</p>
									<a class="btn btn-mini" href="#">» Read More</a>
								</div>
                            </div>
                        </li>
                        <li class="col-sm-3">
							<div class="fff">
								<div class="thumbnail">
									<a href="#"><img src="http://placehold.it/360x240" alt=""></a>
								</div>
								<div class="caption">
									<h4>Praesent commodo</h4>
									<p>Nullam Condimentum Nibh Etiam Sem</p>
									<a class="btn btn-mini" href="#">» Read More</a>
								</div>
                            </div>
                        </li>
                    </ul>
              </div><!-- /Slide3 -->
        </div>


	   <nav>
			<ul class="control-box pager">
				<li><a data-slide="prev" href="#myCarousel" class=""><i class="glyphicon glyphicon-chevron-left"></i></a></li>
				<li><a data-slide="next" href="#myCarousel" class=""><i class="glyphicon glyphicon-chevron-right"></i></li>
			</ul>
		</nav>
	   <!-- /.control-box -->

    </div><!-- /#myCarousel -->

</div><!-- /.col-xs-12 -->

</div><!-- /.container -->
{% endblock %}